### ISSUE TITLE
시사회 관련해서 들어가는 크롤링 형식 입니다.

### ISSUE THREAD

**Issue by kagong** [openhack-freeder/freeder-crawler#5]
분류(영화 등등)
제목
응모 기간 ()
당첨자 발표
시사회 장소 
시사회 시간(날짜 끝에 '~' 이 들어갈 경우 그날 이후로 발표함)
경품
url

해당 사항이  그 영화에 없는 경우는 None으로 처리하겠습니다.

**Comment by gwons** [comment]
None 말고 공백으로 처리해주세요

**Comment by kagong** [comment]
비어있음으로 처리하겠습니다!

**Comment by gwons** [comment]
welldone
